apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-annonsemottak
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-annonsemottak
  port: 9016
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  liveness:
    initialDelay: 20
    path: /isAlive
  readiness:
    initialDelay: 20
    path: /isReady
  resources:
    limits:
      cpu: 2000m
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  webproxy: true
  vault:
    enabled: true
  ingresses:
  - https://pam-annonsemottak.nais.oera.no
